### ISSUE TITLE
Random mystery crash starting and during maps + suspicious explosions

### ISSUE THREAD

**Issue by scrumbo** [MatthewTheGlutton/HideousDestructor#39]
There is an random crash with detonated grenades and underslung rockets.
Diabolus Ex would randomly crash on level start and restarts

It's been happening since using the master version from august - at the earliest point of reference- up to latest.

Crashes would close GZDoom 4.2.0 to the bug report screen, 4.2.1 would randomly close without it
[CrashReport.zip](https://github.com/MatthewTheGlutton/HideousDestructor/files/3622723/CrashReport.zip)

Sorry to not be of more help, currently.

**Comment by MatthewTheGlutton** [comment]
What is the date of the latest master that you tried? I did address one source of explosion-related crashes a couple days ago (some randomized values going into negatives that the system was never designed to handle) so I'm hoping it could have been that.

**Comment by scrumbo** [comment]
Tested again with latest master as of 4 hours ago. Using as standard as possible setup to elimate other variables. Same thing.

**Comment by MatthewTheGlutton** [comment]
What exactly are the steps you are taking? Is it possible to replicate this without any other mods loaded?

**Comment by MatthewTheGlutton** [comment]
I think I fixed it in 69a30dc

**Comment by scrumbo** [comment]
Now testing with Freedoom and current HD master. Issue persists. Map06 may randomly crash on start.

Steps:
Running GZDoom 4.2.1 non-administrator
Using menu, selecting preset loadout Rifleman OR console command to start on FD map06
Using command to reload the map OR using rockets until crash

**Comment by MatthewTheGlutton** [comment]
Can't replicate Map06 start crash. (I'm using the Freedoom autobuild from September 16)

Wasn't able to replicate by GL-spamming on Map29 as of my previous post, where I was getting a crash within the first 10 grenades before that fix.

You're using the underslung GL, right, not literally rockets in rocket mode?

**Comment by scrumbo** [comment]
Yep, underslung

**Comment by scrumbo** [comment]
After extensive experimenting, I can trigger the rocket crash by hitting a pillar in doom2's map06 at an angle... which sometimes doesn't crash. I have no idea.


[save999.zip](https://github.com/MatthewTheGlutton/HideousDestructor/files/3628427/save999.zip)

Set up a save file aimed at the right spot.

**Comment by MatthewTheGlutton** [comment]
I randomly crash at start of Freedoom map08, for what that's worth.

**Comment by MatthewTheGlutton** [comment]
One hypothesis is that I'm just doing way too much stuff in that one function.

I've tried reducing the number of local variables I'm defining when calculating fragmentation size and trajectory and so far I have not reproduced the crash...

**Comment by MatthewTheGlutton** [comment]
Are the level start and explosion crashes both access violations in the crash reports??

**Comment by MatthewTheGlutton** [comment]
Do you remember if you were getting these crashes prior to August 15? That's when the new bullet code was incorporated into A_HDBlast.

**Comment by MatthewTheGlutton** [comment]
After an entire (fortunately slow work) day I am completely at a loss as to what might be causing these crashes.

It should be a GZDoom bug but there's no way to even begin to figure out how to isolate this.

**Comment by MatthewTheGlutton** [comment]
One relatively predictable way to reproduce:
- use the "bltest" item which primary fire is currently set to spam grenades
- go to Freedoom map08, if it doesn't crash then just kill some stuff for a while
- idclev03, hit the wall behind the first zombie as the door is opening

**Comment by MatthewTheGlutton** [comment]
As of c36c1b99ab02e2353aadafc3c8126131822d6b56 the crash should be replicable thus:
* Freedoom, warp to map29
* "iddqd;give bltest; use bltest"
* hold down the fire button while walking over to the first teleporter behind the door
* once you step out, while holding fire the whole time, look up and to the left

**Comment by scrumbo** [comment]
Both crashes result in access violations
Can't recall what I was using in August

It may be the monsters that are causing the crashes. I launched Diabolus Ex again with the _nomonsters_ flag and successfully started the map 20+ times

D2's map06 pillar doesn't crash if I use the _kill monsters_ console command first. I reloaded the save with the monsters dead and went to town with the rockets on that pillar. No crashes in 20+ attempts. Crashed after loaded the save with the monsters still active.

The demons have crash powers.

**Comment by MatthewTheGlutton** [comment]
Just tried the map29 thing now with my local version, confirmed that if I "kill monsters" first I am as yet unable to reproduce the crash.

**Comment by scrumbo** [comment]
Using Diabolus Ex as a quick level start test, c36c1b9 with monsters still triggers the error after 14 attempts without having fired a single rocket.

**Comment by MatthewTheGlutton** [comment]
Can you see if you can replicate the explosion crash with 780900b5ad31ad8958f21f48b58f90b054168fc9 ?

**Comment by MatthewTheGlutton** [comment]
e8b9c8e19eca2a3151e1810635fa742454bcd780 just deletes some possibly misguided optimization that counts wallchunks before continuing. Seems not to crash from explosions either???

**Comment by scrumbo** [comment]
Ignoring the level start thing - _one crash_ just now after going full-turbo michael bay with the bltest weapon for a dozen Freedoom maps with no problems up until then. Starting a fresh map06 and firing on the mob triggered something.

**Comment by MatthewTheGlutton** [comment]
Good to know - I'm going to assume that the start crash and whatever happened on map06 then are distinct issues (or a distinct issue) from the rocket then.

(As for that, I might file GZDoom bug report later - that was some really old code that, however inefficient or unnecessary, worked without problems for a long time)

**Comment by scrumbo** [comment]
There's things I should've thought of doing before reporting, less risk of wild goose chases.

Regarding common elements: Nothing concrete yet, but marines and HERPS are on my list of suspects. They have been occasionally present on maps I recall crashing on.
Will report back if I find time to test more later.

**Comment by MatthewTheGlutton** [comment]
Does this crash ever happen at the very first map that loads after GZDoom is loaded?

**Comment by MatthewTheGlutton** [comment]
Just confirmed this also happens on the very first map that gets loaded after GZDoom starts, so it's not a matter of garbage that's left in RAM when a new level starts.

**Comment by scrumbo** [comment]
Try it with no monsters, it made a difference for my testing. Crashes went away.

The test runs earlier with _no monsters_, while raining explosives through the crashiest maps had zero crashes. Either overhauls fixed it or it wasn't the issue in the first place,

Can't resume testing just yet, and I might be unable to as I'll have to try using a controller (through steam) with GZDoom because my wrist is killing me (not from this)

**Comment by MatthewTheGlutton** [comment]
Thanks for you help with this!

**Comment by MatthewTheGlutton** [comment]
Somehow efforts to simplify code end up making it worse. Or maybe more likely there's no correlation at all.

Posted to ZDF Technical Issues: https://forum.zdoom.org/viewtopic.php?f=50&t=65926

**Comment by scrumbo** [comment]
Dang, it was a like trying to find a straw in a haystack of needles, but glad to help!

(also thanks for making this!!)

**Comment by MatthewTheGlutton** [comment]
Haven't tried just yet, but seems like it's fixed.
Devbuild link for convenience: http://devbuilds.drdteam.org/gzdoom/

**Comment by scrumbo** [comment]
For reference, devbuild from the 24th is an major improvement. Had multiple sessions without encountering any of the above issues.
